### ISSUE TITLE
Filter groups and nodes based on contexts

### ISSUE THREAD

**Issue by TheOnlyMaldred** [lucko/LuckPermsWeb#105]
Wondering if it'd be at all possible to restrict groups/permissions that have contexts to specific to a group or permission.

For instance if I wanted to see groups/permissions ONLY pertaining to my Lobby server or if I wanted to exclude a server from groups/permission view of my `/lp editor`.

Command could look something like...
`/lp editor server=lobby`
`/lp editor server!=lobby`

**Comment by Turbotailz** [comment]
I'm just trying to figure out *how* it should be done.

Will need to somehow do the following:

- create a context filter, somewhere, maybe where the search filter is?
- choose the key to filter by - or allow for multiple?
- as the user enters the desired filter, update in real-time based on what's entered:
  - filter through every inheritance node to check which groups are inherited with a context and display the returned groups where the current groups are shown
  - do we want to show groups that aren't inherited with a context, but contain permissions with the contexts?
- will the groups with contexts show all permissions in that group, or only the ones with the contexts?

These are all questions that run through my mind as I think of how to resolve this. It's not an easy task so I'd appreciate if anyone had any input on it.

**Comment by Andre601** [comment]
My suggestion would be to have a search bar in the editor, where you can search for permissions by default and have something similar to GitHub's filter system in the issues and PR tab, where you can have things like `context-key:<key>` or `context-value:<value>`

Suggestions for possible filter options:
- `context-key`/`context-value`: Searches for a key/value with the specified text in the contexts.
- `expiry`: Searches for permissions with a specific (relative) expiry-time set.
Kind of similar to how discord does it when you search for something before, after or at a date.
- `group`: For searching perms in a specific group. Useful if you have a group with tons of perms)
- `value`: To search for perms with values true or false

Additionally (and only if really possible) maybe make the search allow wildcards so that you could f.e. search for `*.fly` and it would list every perm ending with "fly".

**Comment by Turbotailz** [comment]
Kinda implemented in #324, you can search for context key/values in nodes now.
