### ISSUE TITLE
Sort users alphabetically

### ISSUE THREAD

**Issue by Ma8ician** [lucko/LuckPermsWeb#138]
sort users alphabetically and expand beyond 500 :)

**Comment by Turbotailz** [comment]
Sorting shouldn't be an issue, however there is a reason for a 500 limit I believe. @lucko can probably elaborate on that.

**Comment by Andre601** [comment]
The limit is simply performance I guess.

First of all, would 500+ requests for avatars be a lot and second.... 500 players are a lot!
Like, imagine loading permission data for more than 500 players in a single session. That sure would eat some resources the server has.
So my guess is simply to keep the usage of resources low.

**Comment by lucko** [comment]
No special reason for the 500 limit, other than the line has to be drawn somewhere.

If the editor loaded user/group data on demand, then such a limit would probably not be necessary - but due to the nature of the current system, everything has to be loaded, packaged up by the server, and sent over bytebin to the editor ahead of time. (this is unlikely to change)

Sure, we could increase to 1000, 2000 .... but I think 500 is a sensible limit for now.

**Comment by lucko** [comment]
Limit was increased to 1000 in the latest plugin release, & users are now sorted by weight and then alphabetically :)
