### ISSUE TITLE
Can't access the web editor

### ISSUE THREAD

**Issue by MCK001** [lucko/LuckPermsWeb#144]
Trying to access the web editor gives me this error:

Loading error
Either the URL was copied incorrectly or the session has expired.
Please try again.

I checked the Chrome console and it gave me this error:

Failed to load resource: net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH

Is this an issue with Luckperms/Cloudflare or is it a problem with my connection? Thanks

**Comment by Andre601** [comment]
Please check the following things:
- You created a fresh session. Session is stored for 7 days iirc.
- Make sure your browser allows Javascript to be executed
- If you connect through a VPN, try disabling it to see if it works.
- Use a supported browser. Supporter are: Edge, Chrom, Firefox and Opera iirc

If all of the above won't change anything, then this might be indeed caused by either CloudFlare or perhaps an outdated SSL-certificate which requires renewal.

**Comment by MCK001** [comment]
My session was created about a few seconds ago - I just opened the link from /lp editor. Using chrome and it's worked fine before, only recently started having this problem. Edge, Firefox and Opera don't work either. Do I need to renew the SSL certificate on my end? Other OPs can access it fine

**Comment by MCK001** [comment]
Fixed it, was a problem with my DNS settings.
