### ISSUE TITLE
i have Problem in the WebEditor.

### ISSUE THREAD

**Issue by qetito** [lucko/LuckPermsWeb#151]
Today I went to the editor and I see that there is no line for entering rights, I leafed through for a long time, clicked on groups, tried to restart the laptop, server, used other browsers, but there was no line for input anywhere

**Comment by Turbotailz** [comment]
Seems to be a weird caching issue that's happening since the last deployment I triggered a couple hours ago.

Another person reported the issue here:   
https://github.com/lucko/LuckPerms/issues/2035

I'd suggest doing a hard refresh `ctrl + shift + r` every now and then to try grab the latest files.

**Comment by Turbotailz** [comment]
Confirmed with @lucko that this is indeed a caching issue with Netlify. Will see if there is anything we can do to prevent it happening again in the future.
