### ISSUE TITLE
Permissions Dupe

### ISSUE THREAD

**Issue by kacperleague9** [lucko/LuckPermsWeb#170]
In editor, you can add two the same permissions, i hate it.

**Comment by Andre601** [comment]
I'll just link my response from your issue over at the LuckPerms GitHub
https://github.com/lucko/LuckPerms/issues/2094#issuecomment-602711231

In addition: WHY do you hate it? HOW could we improve it?
We're aware that not everyone likes the editor's functionality and that it may seem a bit buggy. But we would really appreciate if you could give us some constructive feedback on how we could improve it instead of just saying "I hate it"

**Comment by Turbotailz** [comment]
Can you please explain more about how and why you are adding duplicate permissions?

Duplicates are often needed in the case of different contexts but I understand that if a node is exactly the same as another one in the same group then that's probably not ideal (I'm pretty sure they aren't duplicated when you save and apply the changes in LuckPerms, anyway).

**Comment by Turbotailz** [comment]
No response, closing.
