### ISSUE TITLE
Cannot put in multiple worlds in the editor

### ISSUE THREAD

**Issue by KevinW825** [lucko/LuckPermsWeb#211]
In the old luckperms editor, you could put in multiple worlds for a permission when adding them, now its harder to do that and it takes longer to do that, the new editor is extremely worse in situations where you have multiple worlds you need to set. When you try to add in a new world in the context it instead renames the world you set it as. When adding a world, it should not rename the world you set, it instead should be adding that world, I don't understand why it does that, you can just put an x next the the configuration like how you did it to the permissions, the new editor is worse because of that feature and requires to have multiple worlds for the context.

**Comment by Turbotailz** [comment]
This was never a feature of the old editor.

You can't add multiple worlds to a permission. Well, you can, in game, but here's why you shouldn't - all contexts must be satisfied for a permission to be granted, players cannot possibly be in two (or more) worlds at once, so adding another world context to a permission, if it already has one, is completely redundant.

You have to create multiple permission nodes for each world context, this has always been the case with LuckPerms. The new editor actually makes this an easier task now, since you can add multiple permissions in the add bar.
