### ISSUE TITLE
Edits won't work

### ISSUE THREAD

**Issue by Lucifer2626** [lucko/LuckPermsWeb#221]
Every time I add permissions to my default group and save, I try to upload it to my server and it gives me the message: No changes were applied from the web editor

**Comment by Laarryy** [comment]
Are you trying to use the webeditor as a sort of backup retrieval system? The editor only tracks changes since you've typed `lp editor`, meaning if you have a bunch of things showing on your editor but haven't actually changed anything since last time, nothing will actually get applied to the server. 

If that isn't the case, perhaps send your editor link and/or join the discord at https://discord.gg/luckperms

**Comment by Lucifer2626** [comment]
How do I actually make the edits then

**Comment by Laarryy** [comment]
Follow the steps on the wiki's editor page exactly, I suppose would be the best way. The wiki is here on GitHub, just click the wiki tab up top and use the sidebar to navigate to Web Editor

**Comment by Laarryy** [comment]
Oops NVM, wrong repo

**Comment by Laarryy** [comment]
Here's the link https://github.com/lucko/LuckPerms/wiki/Web-Editor

**Comment by Turbotailz** [comment]
Any follow up? Is it working now? Can I close this?
