### ISSUE TITLE
Suggetsion

### ISSUE THREAD

**Issue by rohitrk1557** [lucko/LuckPermsWeb#222]
in web editor , show commands instead of permissions , that selected group can access

**Comment by Turbotailz** [comment]
Permissions typically relate to commands. Nor is it possible for LP to know which commands match to which permission.

**Comment by Andre601** [comment]
That wouldn't really be a good thing, especially since it isn't always 100% clear which command and which permission are connected. It would require some additional "thinking" of LP that could cause performance issues and wouldn't be reliable.
I also can't see a reason why a web editor for a **permission plugin** would need  to display commands.

**Comment by BrainStone** [comment]
The permissions system as it is far superior to what you suggested. Also often a command may require multiple permissions, which then makes what you want either impossible or utterly impractical.  
Additionally permissions can control more than just commands. So those would need to represented in the normal manner. That would just be a huge mess.
And as mentioned LuckPerms is a permissions plugin. Not a command control plugin. LuckPerms is not aware of what functionality any of the permissions have (except its own ones of course).

So while I understand where you are coming from, you should instead just learn to set up permissions.
