### ISSUE TITLE
Web editor does not show all permissions

### ISSUE THREAD

**Issue by PythonCoderAS** [lucko/LuckPermsWeb#353]
My server has a lot of plugins, so there a lot of permission nodes, but the luckperms editor only goes up to the `l` nodes. Can the webeditor show all permissions?

**Comment by Turbotailz** [comment]
This isn't an issue with the web editor. LuckPerms can't simply know every permission every plugin has. There is a cache that is kept from when a server is started which keeps track of all unique permissions that have been checked since start up. The reason you aren't seeing many permissions here is because your server just hasn't checked those permissions since the last time it started.

I would suggest running `/help` to make your server generate a series of permission checks, which should help populate that list.

**Comment by Turbotailz** [comment]
I may have misread your issue actually. The dropdown component defaults to showing 1000 entries, which is probably why it stops at L for you. This doesn't mean the permissions aren't there, the list is truncated. If you type in the dropdown field it will filter the permissions. It's not really meant to be used to just browse through all the permissions - I don't think changing the default limit of 1000 is a great idea IMO.

**Comment by Turbotailz** [comment]
If you want to see all permissions, I suggest using `/lp tree`
